version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "ghcr.io/petrisim/backend:latest"
    container_name: backend
    command: npm start
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "ghcr.io/petrisim/frontend:latest"
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
